# Generated by Django 2.0 on 2020-02-15 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnderecoModel',
            new_name='TabelaEnd',
        ),
    ]
