# Generated by Django 2.0 on 2020-02-15 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispositivo', '0004_remove_tabelaend_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelaend',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='TabelaEnd', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
