# Generated by Django 2.0 on 2020-02-15 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispositivo', '0006_auto_20200215_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelaend',
            name='usuario',
        ),
        migrations.AddField(
            model_name='tabelaend',
            name='ario',
            field=models.ManyToManyField(related_name='TabelaEnd', to=settings.AUTH_USER_MODEL),
        ),
    ]
