# Generated by Django 2.0 on 2020-02-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0010_auto_20200215_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelaend',
            name='modelo',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
