# Generated by Django 2.0 on 2020-02-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0012_audiovideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioVideo',
        ),
        migrations.RemoveField(
            model_name='tabelaend',
            name='modelo',
        ),
    ]
