# Generated by Django 2.0 on 2020-02-22 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0013_auto_20200221_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelaend',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TabelaEnd', to=settings.AUTH_USER_MODEL),
        ),
    ]
