# Generated by Django 2.0 on 2020-02-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0014_auto_20200222_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelaend',
            name='usuario',
        ),
    ]
