# Generated by Django 2.0 on 2020-02-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0016_tabelaend_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelaend',
            name='dono',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
