# Generated by Django 2.0 on 2020-02-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0018_auto_20200224_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelaend',
            name='aparelho',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
